# Generated by Django 5.2.13 on 2026-04-27 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RenameField(
            model_name="user",
            old_name="age",
            new_name="contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
    ]
