# Generated by Django 5.2.13 on 2026-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_rename_age_user_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
